[package]
name = "i-cant-believe-its-not-bsn"
authors = ["Alice I. Cecile"]
version = "0.4.0"
edition = "2021"
repository = "https://github.com/weiyuemin/i-cant-believe-its-not-bsn.git"
license = "MIT OR Apache-2.0"
description = "Tools for spawning entity hierarchies in Bevy"
keywords = ["bevy", "ecs"]

[dependencies]
bevy_ecs = { version = "0.19", default-features = false }
bevy_platform = { version = "0.19", default-features = false, features = [
    "alloc",
] }

[dev-dependencies]
bevy = { version = "0.19" }

[lints.clippy]
alloc_instead_of_core = "warn"
std_instead_of_alloc = "warn"
std_instead_of_core = "warn"
